<?php
use smll\framework\io\Request;

use smll\framework\utils\interfaces\IList;

use smll\framework\helpers\Html;
$request = new Request();
if($model instanceof IList) {
	?>
	
	<ul class="nav nav-pills nav-stacked">
		<?php foreach($model->getIterator() as $pageRef) {?>
		<li><a href="<?php print Html::url($pageRef->getExternalUrl());?>"><?php print $pageRef->getTitle();?></a></li>
		<?php }?>
	</ul>
	
	<?php 
}