<div class="navbar navbar-fixed-top navbar-inverse" style="position: absolute;">
	<div class="navbar-inner">
		<div class="container">
			<span class="brand">Smll MVC</span>
			<ul class="nav">
				<li>
				<?php print Html::actionLink("Home", "index", "Home");?>
				</li>
			</ul>
			<?php if($model->authenticated) {?>
				<ul class="nav pull-right">
					<li>
					<?php print Html::actionLink("Account", "index", "Account");?>
					</li>
				</ul>
			<?php }?>
		</div>
	</div>
</div>