<?php
use yogi\framework\helpers\Html;
?>
<nav class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
		<li>
				<?php print Html::actionLink("Home", "index", "Home");?>
		</li>
	</ul>
	<ul class="nav navbar-nav pull-right">
		<li>
			<?php print Html::actionLink("Account", "index", "Account");?>
		</li>
	</ul>
  </div>
</nav>
