<?php
$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('contentToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
        <h2>Blocks <div class="btn-group">
    <a class="btn dropdown-toggle btn-success" data-toggle="dropdown" href="#">
    <i class="icon-plus-sign"></i>
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li></li>
    </ul>
    </div></h2>
	    <table class="table table-striped">
	        <thead>
	            <tr>
	                <td></td>
	            </tr>
	        </thead>
	    </table>
	</div>
</div>
