<?php
use smll\framework\utils\HashMap;
use smll\framework\helpers\Html;

$layout = 'smll/cms/views/Share/_layout.phtml';
?>

<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('editToolsNav', 'AdminNav', new HashMap());?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
		<?php print Html::beginFormFor($model);?>
		<input type="submit" class="btn" value="Add" />
		<?php print Html::closeForm();?>
	</div>
</div>
