<?php
use smll\framework\io\Request;

use smll\cms\framework\route\Router;

use smll\framework\utils\HashMap;

use smll\framework\helpers\Html;

$layout = 'smll/cms/views/Share/_layout.phtml';
?>

<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('editToolsNav', 'AdminNav', new HashMap());?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Term</th>
					<th>Description</th>
					<th class="pull-right">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php
				foreach($model->terms as $term) {
			?>
				<tr>
					<td><a href="<?php print Html::actionUrl('vocabulary-list-terms', 'Taxonomy', new HashMap(array('vocabulary' => $term->id)));?>"><?php print $term->term;?></a></td>
					<td><?php print $term->description;?></td>
					<td></td>
				</tr>
			<?php }?>
			</tbody>
		</table>
		<div class="span8">
			<?php 
			$r = new Request();
			
			print Html::renderAction('add-term', 'Taxonomy', new HashMap(array('vocabulary' => $model->vocabularyId, 'returnUrl' => $r->getCurrentUri())));?>
		</div>
	</div>
</div>
