<?php
use smll\framework\utils\HashMap;

use smll\framework\helpers\Html;
use smll\cms\framework\helpers\CmsHtml;
$layout = 'smll/cms/views/Share/_layout.phtml';
?>

<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('editToolsNav', 'AdminNav', new HashMap(array('id' => $model->ident)));?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
		<?php print CmsHtml::cmsFormForPage($model);?>

		<input type="submit" class="btn" value="save" />

		<?php print Html::closeForm();?>
	</div>
	<div class="span2">
	    <ul class="nav nav-list">
		    <li class="nav-header">Blocks</li>
		    <li>
		        <ul class="nav nav-list">
		            <li>
		                <div class="block block-attachable">
		                    Block #1
		                </div>
		            </li>
		        </ul>
		    </li>
		</ul>
	</div>
</div>
