<?php
$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('adminToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
    <div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span10">
		<h2>Dashboard</h2>

	</div>
</div>
