<?php
$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('editToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
	    <h2>Pages</h2>
	    <form>
	        
	    </form>
		<table class="table table-striped">
	        <thead>
	            <tr>
	                <th>Title</th>
	                <th>Type</th>
	                <th>Author</th>
	                <th>Status</th>
	                <th>Updated</th>
	                <th>Language</th>
	                <th>Actions</th>
	            </tr>
	        </thead>
	        <tbody>
	            <tr>
	                <td>Lorem Ipsum Dolor</td>
	                <td>GamePage</td>
	                <td>Kw33l</td>
	                <td>Published</td>
	                <td></td>
	                <td>sv-se</td>
	                <td></td>
	            </tr>
	        </tbody>
	    </table>
	</div>
</div>
