<?php
$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('editToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
		<h2>Dashboard</h2>
		<div class="container">
			<div class="span4">
				<h3>Recent content</h3>
				<?php print Html::renderAction('recentContent', 'Content');?>
			</div>
			<div class="span4">
				<h3>Recent user</h3>
				<?php print Html::renderAction('recentContent', 'Content');?>
			</div>
			<div class="span4">
				<h3>Recent comments</h3>
				<?php print Html::renderAction('recentContent', 'Content');?>
			</div>
		</div>
	</div>
	<div class="span2">
		<h5>Number of pages</h5>
		12
		<h5>Number of Users</h5>
		12
	</div>
</div>
