<?php
use smll\cms\framework\helpers\CmsHtml;

use smll\framework\utils\HashMap;

$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('contentToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
	    <?php print CmsHtml::cmsFormForPage($model);?>
	    
	        <input type="submit" value="Save" class="btn"/>
	    
	    <?php print CmsHtml::closeForm();?>
	</div>
</div>
