<?php
use smll\framework\utils\HashMap;

$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('contentToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span8">
	    <h2>Content <div class="btn-group">
    <a class="btn dropdown-toggle btn-success" data-toggle="dropdown" href="#">
    <i class="icon-plus-sign"></i>
    <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
    
    <?php if (isset($model->contentTypes)) {?>
        <?php foreach ($model->contentTypes->getIterator() as $contentType) {?>
            <li><a href="<?php print Html::actionUrl('create', 'Content', new HashMap(array('type' => $contentType->name)));?>"><?php print $contentType->displayName;?></a></li>
        <?php }?>
    <?php }?>
    </ul>
    </div></h2>
	    <table class="table table-striped">
	        <thead>
	            <tr>
	                <td></td>
	            </tr>
	        </thead>
	        <tbody>
	            <?php if (isset($model->contentList)) {?>
	                <?php foreach ($model->contentList->getIterator() as $content) {?>
	                    <?php print_r($content);?>
	                <?php }?>
	            <?php }?>
	        </tbody>
	    </table>
	</div>
</div>
