<?php
use smll\framework\utils\HashMap;

$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('adminToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span2">
		<?php print Html::renderAction('editContentTreeNav', 'AdminNav'); ?>
	</div>
	<div class="span10">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Type</th>
					<th>Assembler</th>
					<th class="pull-right">Actions</th>
				</tr>
			</thead>
			<tbody>
				
			</tbody>
		</table>
	</div>
	<div class="span2"></div>
</div>
