<?php
use smll\framework\utils\HashMap;

$layout = 'smll/cms/views/Share/_layout.phtml';

use smll\framework\helpers\Html;
?>
<div class="row-fluid">
	<div class="span12">
		<?php print Html::renderAction('adminToolsNav', 'AdminNav');?>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>User</th>
					<th>Join date</th>
					<th>Roles</th>
					<th class="pull-right">Actions</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($model->getIterator() as $user) {?>
				<tr>
					<td><?php print $user->membershipData->getProviderName();?></td>
					<td></td>
					<td><?php print join(",", $user->roles);?></td>
					<td>
						<div class="user-actions">
							<div class="btn-group pull-right">
							  <a href="<?php print Html::actionUrl(
							  		'edit',
							  		'User', 
							  		new HashMap(
											array(
												'id' => 
												$user->membershipData->getProviderIdent()
											)
										));?>" class="btn btn-primary"><i class="icon-edit"></i></a>
							  <a href="" class="btn btn-warning"><i class="icon-remove-sign"></i></a>
							  <a href="" class="btn btn-danger"><i class="icon-trash"></i></a>
							</div>
						</div>
					</td>
				</tr>
				<?php }?>
			</tbody>
		</table>
	</div>
	<div class="span2">
		
	</div>
</div>
