<?php 
use smll\framework\helpers\Html;
use smll\framework\utils\HashMap;
?>
<div class="navbar">
	<div class="navbar-inner">
		<div class="container ">
			<ul class="nav">
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown"><i class="icon-user"></i><b class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						<li><a href="<?php print Html::actionUrl('users', 'Admin')?>">Users</a>
						</li>
						<li><a href="<?php print Html::actionUrl('roles', 'Admin')?>">Roles</a>
						</li>
						<li><a
							href="<?php print Html::actionUrl('permissions', 'Admin')?>">Permissions</a>
						</li>
					</ul>
				</li>
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown"><i class="icon-book"></i><b class="caret"></b>
				</a>
					<ul class="dropdown-menu">
						<li><a href="<?php print Html::actionUrl('page-types', 'Admin')?>">Page
								types</a></li>
						<li><a
							href="<?php print Html::actionUrl('block-types', 'Admin')?>">Block
								types</a></li>
					</ul>
				</li>
			</ul>

		</div>
	</div>
</div>
