<?php 
use smll\framework\utils\HashMap;

use smll\framework\helpers\Html;
?>
<div class="">
	<ul class="nav nav-list">
		<li class="nav-header">Site structure</li>
		<li class="active"><a
			href="<?php print Html::actionUrl('edit', 'Cms');?>">/</a></li>
		<li><ul class="nav nav-list collapsible open adminContentMenu"
				id="menu-root">
				<?php
		foreach($model->getItems()->getIterator() as $index => $item) {?>
				<li class="ui-state-default menuItem"
					id="<?php print $item->getId(); ?>">
					<span class="collapse-toggle"
					data-target="#parent-<?php print $item->getId(); ?>"><a href="#">
					<?php if($item->hasChildren()) {?>
					<i class="icon-folder-close"></i>  
					<?php } else {?><i class="icon-minus"></i>
							
					<?php }?> 
					</a> </span>
					<span class="item"><a
						href="<?php print Html::actionUrl($item->getLink(), 'Pages');?>"><?php print $item->getTitle();?>
					</a> </span> <span class="actions"></span>
					<ul
                    	class="sub-nav nav nav-list collapsible closed adminContentMenu"
                    	id="parent-<?php print $item->getId(); ?>">
					<?php if($item->hasChildren()) { print Html::renderAction('secondLevel', 'AdminNav', new HashMap(array('item' => $item))); }?>
					</ul>
				</li>
				<?php }?>
			</ul></li>
		<li class="nav-header">System pages</li>
		<li><a href="#">Profile</a></li>
		<li><a href="#">Settings</a></li>
		<li class="divider"></li>
		<li><a href="#">Help</a></li>
	</ul>
</div>
